disabled_rules:
    - trailing_whitespace
    - for_where
    - colon
    - comma
    - control_statement
    - multiple_closures_with_trailing_closure
opt_in_rules:
    - empty_count
    - empty_string
excluded:
    - Carthage
    - Pods
    - SwiftLint/Common/3rdPartyLib
line_length:
    warning: 150
    error: 1000000000000000
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
identifier_name:
  min_length: 2
  error: 1 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
